### ISSUE TITLE
[1.12.2] Overfilled containers/spilled items

### ISSUE THREAD

**Issue by leonbaronick** [yungnickyoung/YUNGs-Better-Mineshafts#10]
Just installed the 1.12.2 version of your mod into my modpack and figured I'd explore the mineshafts a bit.

Turns out, that chest-minecarts are often over-filled and spill items for some reason.

![2020-07-07_18 33 59](https://user-images.githubusercontent.com/17071279/86851855-f593bb00-c0b3-11ea-8451-5761b3e6c2c3.png)

![2020-07-07_18 33 45](https://user-images.githubusercontent.com/17071279/86851859-f88eab80-c0b3-11ea-8e5c-66ad04410157.png)

Since most of the items that are in the chest and also dropped are vanilla items, I don't think this has anything to do with the other mods of the modpack, but if you need more information on my mod collection, feel free to ask.

**Comment by leonbaronick** [comment]
I can also find a whole bunch of

[Server thread/WARN] [minecraft/LootTable]: Tried to over-fill a container

in the console

**Comment by leonbaronick** [comment]
Turns out that the items that are spilled on the ground are exactly the items inside the chest cart. Perfectly equal.

**Comment by yungnickyoung** [comment]
Hey, thanks for all the info. Seems like I messed something up and somehow chests can get populated multiple times. I'll try to fix this soon.

**Comment by yungnickyoung** [comment]
So far I haven't been able to recreate this. Can you pastebin your mod list?

**Comment by leonbaronick** [comment]
Oh sorry, didn't see the notification until now. I'll send a modlist later or tomorrow. Pretty busy rn.

**Comment by leonbaronick** [comment]
[Made this pastebin](https://pastebin.com/CxxG265S)

Didn't know how to easily get a mod list, so I just used the output of MultiMC.

If you want me to export the MultiMC instance and share it with you I can do that too.

**Comment by AetherBreaker** [comment]
I'm having the same issue it seems.
modlist: https://hatebin.com/toksfjmutw

**Comment by Circine** [comment]
https://github.com/Railcraft/Railcraft/issues/1810
Sounds like this issue to me, although I don't know why AetherBreaker is experiencing it as well without using Railcraft. Happens with just railcraft and vanilla mineshafts too.

**Comment by CovertJaguar** [comment]
I saw this in my personal play world before I installed Better Mineshafts. I'm not 100% sure whether the issue is Railcraft's fault or not, but I can say with some certainty that it has nothing to do with Better Mineshafts.

**Comment by yungnickyoung** [comment]
Apologies, I was never able to recreate this, and as you might have guessed by now I no longer support 1.12.

**Comment by leonbaronick** [comment]
No worries, probably just a really weird mod incompatibility, if you can't recreate it, the issue probably isn't even on your side.

Keep up the great work, love your mods!
