### ISSUE TITLE
[1.16.1/1.16.2] Missing a Mod License

### ISSUE THREAD

**Issue by ghost** [yungnickyoung/YUNGs-Better-Mineshafts#16]
Since Forge added the license requirement once again at some point, the mod is forced to not load, causing the instance to get shut down.  If there's more backend stuff needed to be finished for it to work on 1.16.2, I apologise.

**Comment by yungnickyoung** [comment]
Still work to be done for 1.16.2. Currently release is specifically for 1.16.1
