### ISSUE TITLE
Crash During Loading (1.12.2)

### ISSUE THREAD

**Issue by Noble772** [yungnickyoung/YUNGs-Better-Mineshafts#17]
[crash-2020-09-06_22.37.48-client.txt](https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/files/5180948/crash-2020-09-06_22.37.48-client.txt)

**Comment by mxnmnm** [comment]
A similar report I'm getting https://gist.github.com/mxnmnm/b882d75a01e4053f4c1071cb04ca816a

**Comment by yungnickyoung** [comment]
Are you guys able to use the mod on its own? Having a hard time understanding the cause of this crash.

**Comment by Noble772** [comment]
Yes I can, I'm currently trying to load a few mods at a time until I encounter the crash again.

**Comment by yungnickyoung** [comment]
Thanks, that will be very helpful

**Comment by yungnickyoung** [comment]
I uploaded a test build in #bm-general on Discord, lmk if it works!

**Comment by TCreopargh** [comment]
I'm getting the same crash too, I suppose this version is just broken? I already removed the config files from the old version but it still crashes.

**Comment by mxnmnm** [comment]
The version on discord worked for me so hopefully it works for everyone else as well

**Comment by yungnickyoung** [comment]
2.0.1 should fix this
