### ISSUE TITLE
New 1.12.2 Charm Version breaks the Charm integration.

### ISSUE THREAD

**Issue by brisingraerowing** [yungnickyoung/YUNGs-Better-Mineshafts#20]
As per title.

[Crash Log](https://gist.github.com/BrisingrAerowing/24b29749bfdf32fa1ede111b73708ade)

The new version fixes FutureMC compat, among other things.

**Comment by yungnickyoung** [comment]
You probably have Charm lanterns disabled in the Charm config, while you have Use Charm Lanterns in the Better Mineshafts config enabled.

**Comment by brisingraerowing** [comment]
Charm auto disables its lanterns when Future MC is installed, but that was broken for quite some time after FMC changed its mod id. The newest release fixes that. I usually force Charm's Lantern's anyways.

**Comment by yungnickyoung** [comment]
Try the new v2.1.1 and let me know how it goes!
