### ISSUE TITLE
[1.12.2] Broken with CQR

### ISSUE THREAD

**Issue by SettingDust** [yungnickyoung/YUNGs-Better-Mineshafts#23]
CQR: https://www.curseforge.com/minecraft/mc-mods/cqrepoured
![图片](https://user-images.githubusercontent.com/19922286/95643129-9c3a8e00-0adf-11eb-8331-a32058a09aa4.png)
![图片](https://user-images.githubusercontent.com/19922286/95643164-05220600-0ae0-11eb-9eed-f8ff9faf6ee6.png)
![图片](https://user-images.githubusercontent.com/19922286/95643167-0b17e700-0ae0-11eb-80d7-f3c7b66410b0.png)

The mineshafts will through the dungeons.

**Comment by yungnickyoung** [comment]
This is normal structure overlap, and cannot be prevented.
