### ISSUE TITLE
No Villages Generated when this mod is enabled

### ISSUE THREAD

**Issue by mouse0270** [yungnickyoung/YUNGs-Better-Mineshafts#24]
Basically what the title says, if I have this mod enabled, no villages are generated anywhere on the world map.

Minecraft version 1.16.3
Forge: 34.1.18
Mod: BetterMineshaftsForge-1.16.2-1.0.jar
Seed: 12542 (should spawn within sight of village when turning around)

Just realized this might be because this is for version 1.16.2
But thought I would let you know either way.

**Comment by yungnickyoung** [comment]
Do you have optifine?

**Comment by mouse0270** [comment]
I am, is there an issue with this mod and optifine that stops villages from generating?

**Comment by yungnickyoung** [comment]
No, it's just optifine that's busted right now

**Comment by mouse0270** [comment]
But why does it generate villages if I have optifine enabled and your mod disabled... but when I enable your mod no more villages...

I still get villages with optifine, I don't with your mod.

**Comment by yungnickyoung** [comment]
Optifine has compat issues with virtually every worldgen mod atm. I don't know the reason but I heard they have a bug right now that messes up the registry.
