### ISSUE TITLE
[1.16 Forge] Unsupported registration method causing crash

### ISSUE THREAD

**Issue by TheCurle** [yungnickyoung/YUNGs-Better-Mineshafts#25]
The following configuration:
Forge: 34.1.33
Better Caves: 1.16.2-1.0.3
(Better Mineshafts: 1.16.2-1.0)

Causes a crash with the following log: 
https://pastebin.com/PszY232n

This is caused by this line:
https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/blob/forge-1.16/src/main/java/com/yungnickyoung/minecraft/bettermineshafts/init/ModStructures.java#L79

Registry.register is unsupported and has been for many years. It is an extremely outdated way of registering game items.

event.register should work with the context given, but i do not have time to dig deeper.

- Curle, Forge Triage

**Comment by yungnickyoung** [comment]
Forge locked the Registry.register methods, so now all modders have to register using the Forge functions. Fix will be out later today.
