### ISSUE TITLE
Curse 1.16.4 Compatibility Flag

### ISSUE THREAD

**Issue by kitsu** [yungnickyoung/YUNGs-Better-Mineshafts#28]
I had to update to 1.16.4 Forge 35.0+ because of other mods, but your mod is working fine with the latest versions.  
Can you add the 1.16.4 compatibility flag in Curse?

I'm trying to rebuild a pack in Twitch for release, but it hides all mods without an exact compatibility tag match...

**Comment by yungnickyoung** [comment]
Uh I'm surprised you got it to work. I haven't marked it for 1.16.4 because a lot of people are telling me it crashes on 1.16.4. 

Regardless, official 1.16.4 compat will be added soon and at that time the version will be updated.

**Comment by kitsu** [comment]
1.16.2 - 1.0.1 is running fine under Forge 35.0.7.  
It is a small pack, but also contains Repurposed Structures, and I haven't had any issue.
