### ISSUE TITLE
1.16.4 V1.1 - Some Mineshafts aren't fully generating.

### ISSUE THREAD

**Issue by Jusey1** [yungnickyoung/YUNGs-Better-Mineshafts#30]
On my 1.16.4 server, I tested it a bit and found three Mineshafts and a 4th one via command which wasn't there at all.

2/3 of the ones I did find weren't fully generated at all. One was an frozen Mineshaft under a Spruce Forest with only just the main hallway and nothing else. Just the central hallway. Another I found with an above ground entrance on an island (was a really cool entrance spot imho and I was excited to turn it into my main Mineshaft area) but it was literally just the entrance 'tower' which just led to a dead end.

The final mineshaft is fully generated and working just fine though, so at least out of four, I got one good one in this world so far.

Side note: Does the chests in the new mineshafts still generate the vanilla loot tables for mineshaft or a new loot table? If latter, might want to fix that to avoid mod conflicts.

**Comment by yungnickyoung** [comment]
Can you post some pics? The mineshafts are meant to vary widly in size, and the chance of side tunnels occuring is random, so it's entirely possible this is the result of intended behavior, and you just got kind of unlucky.

Chests use vanilla loot tables.

**Comment by Jusey1** [comment]
After doing some testings in a singleplayer world, you are probably correct on the Snow one and that was just an unlucky mineshaft. I figure out that the messed up ones are only spawning under ocean biomes, such as this one: https://i.imgur.com/C9oHgJg.png , so I am assuming that ocean caves are just destroying mineshafts that spawn under or near oceans.

Under other biomes like desert and plains? They are acting normally.

**Comment by yungnickyoung** [comment]
This behavior is a little janky but intentional. Any piece that would spawn in an ocean biome gets deleted, in order to avoid weird interactions with water that happen when a piece of the mineshaft penetrates the ocean floor (this was a problem in the past).

I know it's not a very elegant solution, but it works out for most normal gameplay.
