### ISSUE TITLE
Chests not generating after config file tweaks

### ISSUE THREAD

**Issue by aapatheticx** [yungnickyoung/YUNGs-Better-Mineshafts#32]
Hello! Ive never messed with configurations or anything, but my games not crashing so I can’t quite get a good reading on what Im going wrong here. 

Basically, I installed a dungeons gear mod and would like items from it to spawn within the mineshaft chests, and within the dungeons gear file I attempted to add “bettermineshafts:chests/mineshaft” but it doesn’t quite seem to work. I would like to know if this is the proper id for the mod, as I can’t really find a specific tutorial on your mod page or the dungeon’s one.

**Comment by yungnickyoung** [comment]
Hey, the chests in my mineshafts use the vanilla abandoned mineshaft loot tables, so you'll need to modify those.

**Comment by aapatheticx** [comment]
Ty!!
