### ISSUE TITLE
[1.16.4 v1.1] Crash during worldgen 

### ISSUE THREAD

**Issue by thevortex** [yungnickyoung/YUNGs-Better-Mineshafts#34]
BetterMineshafts-Forge-1.16.3-1.1
random crashes during worldgeneration

issue arising in All The Mods 6 - pack version 1.3.4c

https://pastebin.com/yZHK5CdQ

the dimension being affected is created via vanilla datapack however generation does work, occasionally this happens, it takes the server down instantly

**Comment by yungnickyoung** [comment]
Is it crashing on the same seed, or different seeds? 

And for a given seed that it does crash on, does it crash on that seed every time, or only sometimes?

**Comment by thevortex** [comment]
seed doesnt seem to affect it, but so far it seems to only happen in this dimension, the datapack json that we are using to generate it is as follows, 99.999% of the time i have no issues seeing mineshafts everywhere, i do a lot of new world creation as well, and it doesnt happen every time, it hasnt happened since the first day i was having trouble with it, but now someone else playing on the pack is getting it too, i have directed them here


+++++++++++++++++++++++


{

  "name": "allthemodium:the_other",
  "type": "allthemodium:the_other",
  "ultrawarm": true,
  "natural": false,
  "fixed_time": 18000,
  "shrunk": true,
  "piglin_safe": true,
  "respawn_anchor_works": true,
  "bed_works": false,
  "has_raids": true,
  "has_skylight": true,
  "has_ceiling": false,
  "ambient_light": 0.15,
  "sea_level": 125,
  "logical_height": 256,
  "infiniburn": "minecraft:infiniburn_nether",
  "coordinate_scale": 8
}

**Comment by FireySnowman** [comment]
I think I have the same issue as thevortex here. Mod version BetterMineshafts-Forge-1.16.3-1.1.jar and I'm playing on the All The Mods 6 pack, version 1.3.6b. [Crash-log](https://pastebin.com/KdsfbPGi)

**Comment by yungnickyoung** [comment]
I attempted a fix at this issue - please try v1.1.1. Will leave this issue open in case you still experience it.

**Comment by Sanguinely** [comment]
https://pastebin.com/vdCy9usV

Still causing crashes

**Comment by yungnickyoung** [comment]
Please try v1.1.1.

**Comment by jeremiahwinsley** [comment]
I can confirm that v1.1.1 fixes the issue for our server.
