### ISSUE TITLE
"Workstation Dungeon" is extremely OP.

### ISSUE THREAD

**Issue by thecanidcoder** [yungnickyoung/YUNGs-Better-Mineshafts#35]
While traversing my local Better Mineshaft, I discovered this room:

![image](https://user-images.githubusercontent.com/22875626/103572993-7a149a00-4e9b-11eb-8497-4e6e91055cbc.png)

This is _extremely_ unbalanced, as it allows a player to make infinite permanently-loyal villagers selling their various items at extremely low prices (usually 1 emerald, for all but the most expensive trades), for virtually no effort. I will be disabling it in my modpacks going forwards, however, I would personally recommend the feature be removed. Finding this "Workstation Dungeon" completely changes your entire game, and I feel that's too much impact for a single feature from a simple mod to improve mineshafts.

**Comment by yungnickyoung** [comment]
Just disable it then. Also this is a zombie villager room / Abandoned Outpost, not a Workstation Dungeon.
