### ISSUE TITLE
Compatibility 

### ISSUE THREAD

**Issue by Thibluedragon** [yungnickyoung/YUNGs-Better-Mineshafts#40]
I'm having a compatibility issue its saying it  for an older version of the game and everywhere I looked I can't find a  update 
<img width="447" alt="Screenshot_222" src="https://user-images.githubusercontent.com/78089213/106000279-a5466f80-607c-11eb-92e7-16ec1061ba92.png">

**Comment by yungnickyoung** [comment]
It's just because I haven't updated the pack format version. It will work just fine.
