### ISSUE TITLE
This mod is causing chunks not to generate/ watch dog exception

### ISSUE THREAD

**Issue by QPCrummer** [yungnickyoung/YUNGs-Better-Mineshafts#43]
[crash-2021-02-09_16.36.19-server.txt](https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/files/5954436/crash-2021-02-09_16.36.19-server.txt)

**Comment by QPCrummer** [comment]
It seems to be caused by an Astromine Asteroid generating.

**Comment by yungnickyoung** [comment]
Yeah, seems like another feature is generating in a manner that causes the server to hang.
