### ISSUE TITLE
Datapack version out of date

### ISSUE THREAD

**Issue by PhantomFailure** [yungnickyoung/YUNGs-Better-Mineshafts#45]
The data pack with the fabric version of the mod is causing errors for my world creation or to join worlds. It keeps saying it is out of date and unable to be used

**Comment by yungnickyoung** [comment]
This is because I use an older pack version, but it should not actually cause any problems besides the red warning message. Will leave this issue open until it is fixed.

**Comment by yungnickyoung** [comment]
Fixed in v1.0.1.
