### ISSUE TITLE
Mineshafts not spawning... 

### ISSUE THREAD

**Issue by JKaiya** [yungnickyoung/YUNGs-Better-Mineshafts#48]
I kept teleporting to random places to check but I could never locate a mineshaft :/ I use this mod with Yungs Better Caves, Extended Caves, Quark, Subterrarian Wilderness, and Biomes O Plenty.

**Comment by yungnickyoung** [comment]
Please provide more info, e.g. version number, complete mod list, logs, etc.

**Comment by JKaiya** [comment]
Pretty sure it was a mod conflict with one of the mods I had., as I got it to work, it's been a little more than a week now so I honestly don't remember what specifically it was... I did however notice that when this mod is combined with Quark and Yungs Better Caves, sometimes the mineshafts/strongholds (or any underground structure) can get cut apart due to the cave generation, which I'm pretty sure is Quark's fault and not Yung's Better Caves

**Comment by yungnickyoung** [comment]
Yeah, I recommend disabling the Mega Caves and Crevices from Quark, as they will destroy any structure they encounter.
