### ISSUE TITLE
Mineshafts can generate floating above the surface in Mesas and even water bodies

### ISSUE THREAD

**Issue by TrueCP6** [yungnickyoung/YUNGs-Better-Mineshafts#5]
![](https://user-images.githubusercontent.com/39642832/83937588-4fac1280-a7ce-11ea-80d7-8d7377b8edc2.png)
Found on version 0.4.1.

**Comment by yungnickyoung** [comment]
Will be fixed in 1.0. I'll leave this issue open until it's out.
