### ISSUE TITLE
Mineshafts don't spawn in superflats

### ISSUE THREAD

**Issue by ghost** [yungnickyoung/YUNGs-Better-Mineshafts#53]
Forge 36.0.55
BetterMineshafts-Forge-1.16.4-2.0.2
YungsApi-1.16.4-Forge-4

https://imgur.com/a/kv5NnHp
my variants.json config https://pastebin.com/2a24H820

As you can see from the image a normal overworld creates mineshafts as you would expect (I drastically increased the minecart chest spawns and other features)

But when you create a world using the Vanilla Superflat World Desert preset the mineshafts appear normal, bland and boring

is this a bug?  Im aiming for a desert world with mineshafts with stone, moss, vines, cactus and mushrooms

**Comment by yungnickyoung** [comment]
EDIT: Ignore my original comment.

Better Mineshafts currently intentionally don't spawn in superflats. Honestly, it's been so long since I made that decision, I can't remember why I made it. I can look into adding an option for enabling BM in superflats.

**Comment by ghost** [comment]
if its easy to implement it would be nice.  Im trying to create a pack like Forever Stranded. Most of the world is sand. I thought BetterMineshafts would spice up the world a bit  :-)

Im guessing if I use a mod like Topography to create a desert world, would BetterMineshafts still work?

**Comment by yungnickyoung** [comment]
Ultimately decided against it as it introduced complications.
