### ISSUE TITLE
Better Mineshafts needs "yungsapi"

### ISSUE THREAD

**Issue by BlockBrick1** [yungnickyoung/YUNGs-Better-Mineshafts#55]
When I was trying to load both bettermineshafts and bettercaves, forge keeps sending a message telling me "Mod bettercaves requires "yungsapi" 1.16.4-Forge-3 or above. Currently, "yungsapi" is not installed." Do any of you have an idea how to fix this error??

**Comment by yungnickyoung** [comment]
Download YUNG's API... https://www.curseforge.com/minecraft/mc-mods/yungs-api
