### ISSUE TITLE
Incompatibility with better caves yung mod [fabric 1.16.5]

### ISSUE THREAD

**Issue by Kiryonn** [yungnickyoung/YUNGs-Better-Mineshafts#56]
Since i couldn't find a mineshaft in survival, i tried to go on a creative new world. And i found that the mineshafts existed, but like, it was just an little alley with a tnt minecart. That was all. Like it was really tiny.
    I tried to find a new one (after all it could have been bad luck), and i found no mineshaft where i teleported.
    Then i checked the mod config and saw the generation y and thought that maybe the caves generation were overriding the mineshaft.
    So i tried to desactivate the better caves mod, and guess what ? It worked. It's probably the same on the forge version since i couldn't find any mineshaft either with only your mods on. Didn't tested it tho.

**Comment by yungnickyoung** [comment]
Hey, all my mods are fully compatible with each other. You may have found a Quark crevice or mega cave, which are notorious for overwriting other modded structures. My caves will not overwrite the mineshafts, or any other structure, because they generate before anything else.
