### ISSUE TITLE
[Feature Request] Dimension Support

### ISSUE THREAD

**Issue by Winddbourne** [yungnickyoung/YUNGs-Better-Mineshafts#57]
I downloaded this mod to go with your better caves mod, and that one allows me to white list dimensions. I'm doing a skyblock pack right now but I have a mining dimension and I've configured the caves to generate there in a very specific way. 

It also has a custom biome. It's the Advanced Mining Dimension mod, and I've customized it a bit with a data pack. 

If I could customize the mineshafts to only generate there I would have their spawn values be set to about twice the default. Thirty Four to Seventy Four is horrible for a normal Overworld but might still be a bit narrow when the stone layer goes up to world height. 

I'm fairly sure these won't generate in my custom overworld as it has a custom biome that doesn't support mineshafts at all but I'm not sure about other dimensions. I'm going to have to check them one at a time. 

I also notice that the mining dimension uses only a single custom biome and it would be nice to have a setting that tells this mod to pick from a random list rather than using the biome settings for dimensions like that.  It would add variety.

**Comment by yungnickyoung** [comment]
I agree it could use some better control options.

Note that the mineshafts will spawn in all biomes that have vanilla mineshafts added to them. So, you should be able to directly control where the mineshafts spawn via datapack.

**Comment by Winddbourne** [comment]
Good point and while that is a lot of work it definitely is something I can do. It's easy for me since what I'm working on is the next update for [Nightfall](https://www.curseforge.com/minecraft/modpacks/nightfall2). My Overworld is a single biome, so are both the mining dimension, and Ratlantis. 

I can check them easily and set up a datapack but I'd be surprised if mineshafts spawn anywhere outside the mining dimension right now. The real problem is going to come for people who want to recreate this sort of mining dimension but they also have a normal world with something like Biomes of Plenty installed. 

I probably could have made it work, and I will, but I'm also glad my first instinct was to say something. I've been working on packs for a long time now and I feel a lot better making this work knowing that you agree and are working on the problem. My next pack may use those control options! :)

**Comment by yungnickyoung** [comment]
Closing this since structures and dimensions interact in much different ways in 1.18 than they used to.
