### ISSUE TITLE
Option to force a surface entrance on every mineshaft

### ISSUE THREAD

**Issue by voidsong-dragonfly** [yungnickyoung/YUNGs-Better-Mineshafts#59]
As title says, and 1.12 if possible. Would have done a PR but got confused by the code determining if one spawned or not.

**Comment by yungnickyoung** [comment]
Surface entrances require fairly significant surface conditions to spawn. They already spawn as much as possible, given those conditions. In future releases (for MC 1.18+) I may revisit the surface entrance logic to clean it up and make it more customizable. But existing versions will not be receiving such an overhaul.

**Comment by voidsong-dragonfly** [comment]
Cool, no problem then. Makes sense
