### ISSUE TITLE
I have a trouble, when i try to launch the game it always write that this mod requires yungsapi 

### ISSUE THREAD

**Issue by RakhatCommie** [yungnickyoung/YUNGs-Better-Mineshafts#60]

**Comment by Lunatorki** [comment]
I have the exact same issue. Just downloaded it off cursefoge.com
Mod version: Yung's better mineshafts v2.0.3
forge version: 36.1.24 for minecraft 1.16.5

**Comment by Lunatorki** [comment]
> 
> 
> _No description provided._
I had the same issue and went looking. 

I looked through their other projects and they had a mod called Yung's API and it gave a list of all of their mods that require the API.  It solved my issue. I have included a link if you haven't solved yours yet.
https://www.curseforge.com/minecraft/mc-mods/yungs-api

**Comment by Lunatorki** [comment]
> 
> 
> _No description provided._



I had the same issue and went looking.
I looked through their other projects and they had a mod called Yung's API and it gave a list of all of their mods that require the API. It solved my issue. I have included a link if you haven't solved yours yet.
https://www.curseforge.com/minecraft/mc-mods/yungs-api
