### ISSUE TITLE
[Suggestion] Have something similar to Save my Stronghold! for Mineshafts

### ISSUE THREAD

**Issue by starryfae** [yungnickyoung/YUNGs-Better-Mineshafts#67]
A particularly egregious example of torn up mineshafts comes from Quark's Mega Caves, floating vines/mineshaft parts throughout the cave, a feature to prevent this would be fantastic, understandable if it isn't possible

**Comment by yungnickyoung** [comment]
It's not possible. This can only be fixed on Quark's end. I recommend disabling Quark mega caves and crevices.

**Comment by starryfae** [comment]
Thanks for the quick response ^^
