### ISSUE TITLE
Mineshafts not spawning

### ISSUE THREAD

**Issue by Veliz2510** [yungnickyoung/YUNGs-Better-Mineshafts#69]
Minecraft Versión: 1.16.5

Forge Versión: 1.16.5-forge-36.2.2

Mod Versión: BetterMineshafts-Forge-1.16.4-2.0.4

Mods I have installed: 
1. BetterMineshafts-Forge-1.16.4-2.0.4
2. YungsApi-1.16.4-Forge-12

My problem is that by creating a new world, Mineshaft doesn't spawn.
I try to search with the /locate command but when I use the command I get the following message ''Could not find that structure nearby'' It don't matter if I walk a thousand blocks they never spawn.

![2021-08-09_03 15 33](https://user-images.githubusercontent.com/88647176/128666431-57525191-ac8c-4a2f-b204-f28e80e1a516.png)

**Comment by yungnickyoung** [comment]
The command is `/locate bettermineshafts:mineshaft`. Try that and see if it works
