### ISSUE TITLE
[BUG / FORGE / 1.16.5] Custom variant mineshafts not spawn as intended.

### ISSUE THREAD

**Issue by KKotik** [yungnickyoung/YUNGs-Better-Mineshafts#74]
Custom variant mineshafts not spawn as intended. In spawnchunks I am getting a mineshaft made of air, if I am using modded blocks. (Darker Depths in my case)
The issue looking like this and so far appearing only in spawn chunks:
![image](https://user-images.githubusercontent.com/45950781/143500524-2e931ecd-8d52-477e-b563-b45823d83a7b.png)
And this is how it should looking, and looking outside of spawn chunks already:
![image](https://user-images.githubusercontent.com/45950781/143500548-8cf4fa54-29a3-40fe-819b-5b83086d214e.png)
Log files when issue is happens:
[debug.log](https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/files/7605245/debug.log)
[latest.log](https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/files/7605247/latest.log)
Sometime crash report:
[crash-2021-11-25_12.59.20-server.txt](https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/files/7605252/crash-2021-11-25_12.59.20-server.txt)
The configs (.txt for github only):
[bettermineshafts-forge-1_16.txt](https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/files/7605255/bettermineshafts-forge-1_16.txt)
[variants.txt](https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/files/7605256/variants.txt)

**Comment by yungnickyoung** [comment]
This was likely an issue with how I initialized blocks from the config. *Should* be fixed in 1.18 but feel free to open another issue if it persists.
