### ISSUE TITLE
BetterMineshaft crashed Error multiple times

### ISSUE THREAD

**Issue by Klouver-github** [yungnickyoung/YUNGs-Better-Mineshafts#76]
I was trying that new cool whip mod that you showed us in the VIP early access and It won't let me pass

**Comment by yungnickyoung** [comment]
You need to get the latest version of YUNG's API from the VIP as well. Also please don't open issues here for closed betas - you can just bring it up in the VIP channel on Discord!

**Comment by Klouver-github** [comment]
sorry Yung, I have taken out my paste.gg link
