### ISSUE TITLE
Incompatibility with Caves & Cliffs Backport (1.16.5, Forge)

### ISSUE THREAD

**Issue by BloodyNecroZ** [yungnickyoung/YUNGs-Better-Mineshafts#79]
When both mods are installed, as pointed out on the "Caves & Cliffs Backport" known issues, regular minecraft:mineshafts start spawning. When on a server, it can cause corrupted chunks, as shown on the text filed attached.
[error.txt](https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/files/8467553/error.txt)

~The error above causes the chunk not to save anything done there, and I suspect its directly tied to the "Dripstone Cave" biome from "Caves & Cliffs Backport" as I've not seen it happen on any other biome. After editing the config file of said mod to make the "Dripstone Cave" biome not get generated, the issue seems to get resolved.~ Not true, error also happens on biome "cavebiomeapi:caves"

Steps to reproduce:
- Have both mods
- Use a chunk pregenerator like "Chunky Pregenerator"
- Generate a decent amount of block radius (the first 2k block radius didn't throw me the error, it was only thrown after 3k blocks)
- Watch out for the "Failed to save chunk error" and teleport to said chunk by multiplying coordinates shown by 16.
- Should look like this, an ore room connected to a regular minecraft:mineshaft. Was the same on every single error I had:
![ore room](https://user-images.githubusercontent.com/40871880/162828971-7cce2c17-d5d4-4074-890c-4d4891068692.png)

**Comment by BloodyNecroZ** [comment]
Also, don't know if related or not, but with both mods there seems to be a really low amount of chests getting generated on the mineshafts

**Comment by yungnickyoung** [comment]
That ore room is part of the C&C Backport mod's mineshafts. If BlackGear wants compat w/ Better Mineshafts, they can implement it in a manner similar to how Repurposed Structures does it. Unfortunately I can't help too much here since C&C Backport is not open source.
