### ISSUE TITLE
[Bug report] Mineshafts do not spawn in TerraForged world type

### ISSUE THREAD

**Issue by Quizer9O8** [yungnickyoung/YUNGs-Better-Mineshafts#8]
How to reproduce:
1. Install TerraForged alongside Better Mineshafts
2. Start up the game, create a new world, select TerraForged
3. type in the command `/locate Mineshaft` and teleport to the cordinates given
You won't find any Mineshaft in the area.

**Comment by RedMoikle** [comment]
Good to see I am not the only one. Thought I must just be really unlucky since people have been saying this supports most worldgen mods.

**Comment by yungnickyoung** [comment]
This was a while back and was resolved on Discord I believe. Will open it back up since there are other reports of this happening again.

**Comment by notfoundry** [comment]
My experience has been that if you generate a world with default worldgen first, exit that world, and generate a world with terraforged worldgen, the mineshafts will show up in the "Structure Settings" menu and will generate correctly in the world.

The error that shows up in the console during load seems to consistently be `Structure bettermineshafts:mineshaft has been added to 71 biomes but has no separation settings registered for it! We may not be able to generate/locate it :[`

**Comment by ProfessionaFiddler** [comment]
Reporting the same, tried everything :(

**Comment by Won-Ton** [comment]
Hi, TerraForged can only use `StructureSeparationSettings` that have been registered in `WorldGenRegistries.DIMENSION_SETTINGS` or that have been added via datapack.

There's a code snippet on our wiki that should help if you'd like to do that:
https://github.com/TerraForged/TerraForged/wiki/Mod:-Structures:-Compatibility#snippet

**Comment by RedMoikle** [comment]
You know I think the latest version of one or both of these mods may have fixed the issue. I updated both, and my current world does actually generate them.

**Comment by Won-Ton** [comment]
Ah yeah, the settings are probably being registered correctly then but it could be happening too late for TF to use them the first time you create a world. By the time you create a second world (or perhaps reopen the first one) the settings are properly registered and available for use (this is what notfoundry described as well, looking back at it)

**Comment by ProfessionaFiddler** [comment]
> Hi, TerraForged can only use `StructureSeparationSettings` that have been registered in `WorldGenRegistries.DIMENSION_SETTINGS` or that have been added via datapack.
> 
> There's a code snippet on our wiki that should help if you'd like to do that:
> https://github.com/TerraForged/TerraForged/wiki/Mod:-Structures:-Compatibility#snippet

Could you please give some directions on how to add the mod structure and where to add it?

**Comment by Won-Ton** [comment]
> Could you please give some directions on how to add the mod structure and where to add it?

The thing I linked are the directions - it's information for mod developers. it's not something end-users can add, sorry

**Comment by ProfessionaFiddler** [comment]
Welp, ok. We should expect it to be fixed in next release I presume then?

**Comment by yungnickyoung** [comment]
Fixed in v2.0.2.
