### ISSUE TITLE
Better Mineshafts log spam "Detected setBlock in a far chunk"

### ISSUE THREAD

**Issue by Jukabofy** [yungnickyoung/YUNGs-Better-Mineshafts#80]
[latest.log](https://github.com/YUNG-GANG/YUNGs-Better-Mineshafts/files/8612020/latest.log)
Seems to lost something and then it stop anytime

1.18.2
Last version of Yung's api
Forge 40.1.0

**Comment by Jukabofy** [comment]
Yung mods that I have currently are Strongholds, Dungeons and the Api, this one seems to stop the TPS of the game, once I delete this mod, it did not stop again, just it for the moment
![2022-05-03_16 13 20](https://user-images.githubusercontent.com/87483832/166568373-8f5a5102-eb73-42c9-9309-4a2bb090b067.png)
I wasn't able to reach this part of my world, until I deleted it.
* The world was created before i put these mods in yesterday

**Comment by Jukabofy** [comment]
Looks like it's solved with the last version of Yung's API, at least the TPS problem and chunkbuilder, Closing...

**Comment by Jukabofy** [comment]
[latest.log](https://github.com/YUNG-GANG/YUNGs-Better-Mineshafts/files/8627313/latest.log)
Idk why, but it still show me the same problem.
"[16:25:17] [Worker-Main-37/ERROR]: Detected setBlock in a far chunk [-2271, -328], pos: MutableBlockPos{x=-36333, y=-48, z=-5248}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/configured_structure_feature / bettermineshafts:mineshaft_acacia]"

**Comment by nikijaz** [comment]
I can confirm. Also have latest version of YUNGS API and bettermineshafts.

**Comment by yungnickyoung** [comment]
Seems like this is a result of me using the PlacedFeatures for dripstone & lush mineshafts. It shouldn't actually cause any issues aside from the log spam, but I'm looking into a fix.

**Comment by yungnickyoung** [comment]
@Jukabofy I think your deadlock issue was probably due to something else

**Comment by yungnickyoung** [comment]
Looks like it's actually a more widespread issue than I thought. In the meantime, I've implemented a hotfix to suppress the log spam in v2.1.1.
