### ISSUE TITLE
"Experimental settings" warning screen on a clean instance with nothing else installed

### ISSUE THREAD

**Issue by ccrowles** [yungnickyoung/YUNGs-Better-Mineshafts#81]
As per title, I get the experimental settings warning even on a clean world in a clean instance with nothing else installed aside from Better Mineshafts and Yung's API.
Minecraft version: 1.18.2
Forge version: 40.1.16

Logfile: [latest.log](https://github.com/YUNG-GANG/YUNGs-Better-Mineshafts/files/8645047/latest.log)

PolyMC logfile: [here](https://0x0.st/omos.txt)

Screenshots:
![Screenshot_2022-05-07_13-42-34_194](https://user-images.githubusercontent.com/12866474/167252964-9f40320e-e01e-49ba-a5d1-bdf878ba9913.jpg)
![Screenshot_2022-05-07_13-43-20_466](https://user-images.githubusercontent.com/12866474/167252966-3c4c3660-2a41-41fc-b687-0687640fcfd5.jpg)

**Comment by yungnickyoung** [comment]
Addressed in Better Strongholds issue.
