### ISSUE TITLE
Crash due to attempting to apply Direction property to sugar cane during SideRoom generation

### ISSUE THREAD

**Issue by Nechronom** [yungnickyoung/YUNGs-Better-Mineshafts#82]
Myself and a friend of mine were playing on a (admittedly heavily modded based upon the modpack: Create Flavored, with the addition of a couple on the side) young minecraft server run by a third friend of ours. To the best of my knowledge, this is either something about an overlap of the mineshafts, or something weird about something trying to place sugarcane? 
Please let me know if there's any further information that you'd like to request. And I apologize in advance for the length of these.
 
https://paste.gg/p/anonymous/d07152f224e84faf8430d34a6e7a9da5/files/96978c768021437eb13f26b37a51b829/raw
The Crash Log: https://paste.gg/p/anonymous/5a20c352e00a4dfb8ec87b9d1de329be

**Comment by Darlos9D** [comment]
Server owner here. It's happened a few more times and its definitely related to sugarcane. Namely whatever is going on here, as this is part of the log every time:

> 10.05 17:29:08 [Server] INFO Caused by: java.lang.IllegalArgumentException: Cannot set property DirectionProperty{name=facing, clazz=class net.minecraft.core.Direction, values=[north, south, west, east]} as it does not exist in Block{minecraft:sugar_cane}
10.05 17:29:08 [Server] INFO at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:117) ~[server-1.18.2-20220404.173914-srg.jar%23123!/:?] {re:mixin,re:classloading,pl:mixin:APP:ferritecore.fastmap.mixin.json:FastMapStateHolderMixin,pl:mixin:A}
10.05 17:29:08 [Server] INFO at com.yungnickyoung.minecraft.bettermineshafts.world.generator.pieces.SideRoom.m_183269_(SideRoom.java:151) ~[YungsBetterMineshafts-1.18.2-Forge-2.1.0.jar%23119!/:1.18.2-Forge-2.1.0] {re:classloading}

We're running:
-YungsBetterMineshafts-1.18.2-Forge-2.1.0.jar
-YungsApi-1.18.2-Forge-2.0.8.jar
-forge-1.18.2-40.1.19-server.jar

**Comment by yungnickyoung** [comment]
Not sure what's causing this, but I'm adding an additional check to prevent this crash.

**Comment by yungnickyoung** [comment]
Attempted a fix in v2.1.3. Let me know if it works for you!

**Comment by Nechronom** [comment]
Sorry about the lack of response. Yea we'll try it out next time we think about updating the mods. Sorry if that takes some time. I was unable to replicate the issue in single player, as it's no doubt a rare and weird circumstance to occur. And we've yet had to mental fortitude to try re-adding the mod to the pack just yet.

**Comment by yungnickyoung** [comment]
Appears to be resolved.
