### ISSUE TITLE
[ Feature request (?) ] Possibility to disallow different dimensions

### ISSUE THREAD

**Issue by TheAyes** [yungnickyoung/YUNGs-Better-Mineshafts#84]
Better mineshafts makes them spawn in the aether aswell... which looks kinda cool but breaks immersion. So either a config entry like you have for the bridges. or just straight up disable spawning in `the_aether:the_aether`. :)
![image](https://user-images.githubusercontent.com/68541335/171812760-4fda1bb2-9246-4266-8bba-5164dce021bb.png)

**Comment by yungnickyoung** [comment]
Past versions of Minecraft handled structure spawning in very non-user-friendly ways. I no longer support pre-1.18 and as such this won't be fixed, but dimension stuff can be fully customized to fix your problem in newer versions (1.18+) via data pack
