### ISSUE TITLE
OutOfMemory when `/locate minecraft:mineshaft`

### ISSUE THREAD

**Issue by spoorn** [yungnickyoung/YUNGs-Better-Mineshafts#86]
In my modpack that includes BetterMineshafts: https://www.curseforge.com/minecraft/modpacks/spoornpack-fabric
I noticed when I do a `/locate minecraft:mineshaft`, the RAM spikes up (> 12GB) until it runs out and the game freezes/crashes.  Removing BetterMineshafts fixes this.

If I download just BetterMineshafts, it just can't locate any but doesn't spike up as much (like https://github.com/YUNG-GANG/YUNGs-Better-Mineshafts/issues/69)

Not sure if it's running out of memory because it takes so long searching for a mineshaft and can't find one, or if it's an infinite search due to a conflict with another mod

**Comment by yungnickyoung** [comment]
It should _eventually_ resolve the command, usually after a minute or so. Weird that it doesn't for you. Starting in 1.19, `/locate structure mineshaft` will be short-circuited with Better Mineshafts installed, so it should no longer cause issues.
