### ISSUE TITLE
Spruce Mineshafts generate with WAY too many spruce leaves

### ISSUE THREAD

**Issue by Moofellow** [yungnickyoung/YUNGs-Better-Mineshafts#87]
![2022-06-21_20 05 25](https://user-images.githubusercontent.com/72464266/174922003-e848bd29-0100-43a4-ac62-d2594c856bfa.png)
![2022-06-21_20 05 14](https://user-images.githubusercontent.com/72464266/174922004-4dbc7a4f-9ab9-4a74-8060-048f7a2f4987.png)
![2022-06-21_20 05 03](https://user-images.githubusercontent.com/72464266/174922006-6f0c6a97-2cfc-4eb4-9167-fdcd9f744f10.png)

**Comment by yungnickyoung** [comment]
This is an Overgrown Mineshaft, so uh, yeah this is intended lol. Feel free to stop the structure from spawning via data pack if you don't like it! You can do that by replacing the structure_set `mineshafts.json` with a version of the JSON that doesn't have the `mineshaft_forest` entry. See https://github.com/YUNG-GANG/YUNGs-Better-Mineshafts/blob/multiloader/1.18/Common/src/main/resources/data/bettermineshafts/worldgen/structure_set/mineshafts.json

Feel free to join the Discord if you need help!

**Comment by Moofellow** [comment]
Oh, wasn't aware such a thing existed. My bad!
