### ISSUE TITLE
Ore clusters can spawn with misaligned Pressure Plate

### ISSUE THREAD

**Issue by NielsPilgaard** [yungnickyoung/YUNGs-Better-Mineshafts#89]
Source: https://github.com/EnigmaticaModpacks/Enigmatica6/issues/5104

- using `BetterMineshafts-Forge-1.16.4-2.0.4`

**Comment by yungnickyoung** [comment]
Apologies, I never saw this. Better Mineshafts doesn't have any such trap in the structure, so it must be another mod's structure that perhaps intersected a Better Mineshaft

**Comment by NielsPilgaard** [comment]
Alright 👍 thanks.
