### ISSUE TITLE
1.12.2 Crash Exception generating new chunk

### ISSUE THREAD

**Issue by StormbringerGTX** [yungnickyoung/YUNGs-Better-Mineshafts#9]
Hey Nick! Caught a snag whilst testing our modpack:

https://pastebin.com/R8XmEGxb

Essentially the game crashed as I wandered and was generating new chunks.

**Comment by yungnickyoung** [comment]
Well that's interesting.. certainly a weird place to crash. Looks like it might be unrelated to the mineshafts, although I'm not sure how it could possibly crash there either way. I'll look into it.

**Comment by StormbringerGTX** [comment]
I THOUGHT I posted this in the better caves git, apologies!

**Comment by yungnickyoung** [comment]
Lol no worries. Has this kind of thing happened more than once? It's a seriously weird place for a crash to occur.

**Comment by StormbringerGTX** [comment]
Could be a quirk, but so far in testing, no it has not happened again.

**Comment by yungnickyoung** [comment]
Hey, if this still hasn't happened again I'm gonna close the issue. Super weird crash and the source of the problem definitely wasn't Better Caves. It should be completely impossible for the provided values at the point of the crash to generate a NPE, so another mod must be doing some pretty jank stuff before passing it on to Better Caves.
