### ISSUE TITLE
Mineshaft generates through aquifers

### ISSUE THREAD

**Issue by Eatham532** [yungnickyoung/YUNGs-Better-Mineshafts#91]
![2022-10-04_21 42 17](https://user-images.githubusercontent.com/78714349/193945867-f33895af-688d-4fea-9bf7-2c1733c6771b.png)

Version: 1.19, V 3.1.2

**Comment by yungnickyoung** [comment]
This is intended. They should be closing off to prevent water flowing through the sides, which appears to be the case in the picture.

**Comment by Eatham532** [comment]
Ok, It just feels weird seeing a big rectangle in the middle of the water.

**Comment by yungnickyoung** [comment]
Welp, that's Minecraft worldgen for ya, and unfortunately this is the best option we've got lol
