### ISSUE TITLE
Mineshafts are not generated with William Wythers' Overhauled Overworld

### ISSUE THREAD

**Issue by ghost** [yungnickyoung/YUNGs-Better-Mineshafts#94]
When entering the command `/locate structure #bettermineshafts:better_mineshafts` or any other command to search mineshaft game "hangs" until the next run. By manual search, I also found nothing.

According to a comment on Curseforge, the same problem exists on the Forge version.

![image](https://user-images.githubusercontent.com/118481158/202551094-e15c55f4-29d8-4030-b05a-bdfc66d7a943.png)

1.19.2, Fabric 0.14.10
Better Mineshafts 3.2.0
WWOO 3.1.8

**Comment by yungnickyoung** [comment]
Better Mineshafts uses both Forge and Fabric tags to add itself to biomes. While manually supporting WWOO biomes is an option, imo it would be more appropriate for them to add their biomes to vanilla, Forge, and Fabric tags as Terralith does to ensure compatibility with other mods and data packs.
